#!/bin/bash

# Redis CLI 智能补全演示脚本

echo "=== Redis CLI 智能补全功能演示 ==="
echo ""
echo "1. 编译项目..."
cargo build --release

echo ""
echo "2. 启动说明："
echo "   - 在另一个终端启动 Redis 服务器"
echo "   - 然后运行: ./target/release/rredis-cli.exe localhost"
echo ""
echo "3. 智能补全功能演示："
echo ""
echo "   a) 命令补全："
echo "      输入 'ge' 然后按 Tab 键 → 自动补全为 'GET'"
echo "      输入 'se' 然后按 Tab 键 → 自动补全为 'SET'"
echo ""
echo "   b) Key 补全："
echo "      输入 'GET ' 然后按 Tab 键 → 显示所有可用的 key"
echo "      (需要先在 Redis 中创建一些 key)"
echo ""
echo "   c) 参数补全："
echo "      输入 'CONFIG ' 然后按 Tab 键 → 显示 'GET', 'SET', 'RESETSTAT'"
echo "      输入 'INFO ' 然后按 Tab 键 → 显示各种信息类型"
echo ""
echo "   d) 值补全："
echo "      输入 'SET mykey ' 然后按 Tab 键 → 显示常用值建议"
echo "      输入 'SET mykey \"value\" ' 然后按 Tab 键 → 显示选项 'EX', 'PX', 'NX', 'XX'"
echo ""
echo "4. 支持的命令类型："
echo "   - 基础命令: GET, SET, DEL, KEYS, EXISTS, TYPE, TTL, EXPIRE"
echo "   - Hash 命令: HGET, HSET, HDEL, HGETALL"
echo "   - List 命令: LPUSH, RPUSH, LPOP, RPOP, LLEN"
echo "   - Set 命令: SADD, SREM, SMEMBERS, SCARD"
echo "   - Sorted Set 命令: ZADD, ZREM, ZRANGE, ZCARD"
echo "   - 服务器命令: INFO, CONFIG, PING, FLUSHDB, FLUSHALL"
echo ""
echo "5. 其他功能："
echo "   - 使用 'help' 命令查看所有可用命令"
echo "   - 使用上下箭头键浏览命令历史"
echo "   - 使用 'quit' 或 'exit' 退出"
echo ""
echo "=== 演示完成 ==="